# 服务端口
server:
  port: 1913
  servlet:
    context-path: /system

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.202.135:1653/security_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: P@ssw0rd2024
  redis:
    host: 139.9.202.135
    port: 3189
    password: redis-3189
    lettuce:
      pool:
        # 最大连接数 默认为8
        max-active: 8
        # 最大空闲连接 默认0
        max-wait: 10000ms
        # 最大连接阻塞等待时间
        min-idle: 1
