# 服务端口
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Spring 配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.9.202.135:1653/security_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: P@ssw0rd2024
  redis:
    host: 139.9.202.135
    port: 3189
    password: redis-3189
    lettuce:
      pool:
        # 最大连接数 默认为8
        max-active: 8
        # 最大空闲连接 默认0
        max-wait: 10000ms
        # 最大连接阻塞等待时间
        min-idle: 1

# mybatis-plus
mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    db-config:
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: true # 关闭控制台的 Banner 打印
  # 不支持多包, 如有需要可在注解配置 或 提升扫包等级
  # 指定加载Mapper.xml文件路径
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 指定扫描实体类的包路径
  type-aliases-package: com.wick.module.*.model.entity


# 日志模式、保存路径和文件名
logging:
  level:
    com.wick.module.*: debug
  file:
    name: ./logs/wick-admin-log.log